<<<<<<< HEAD
name = "project"
=======
name = "CS370"
>>>>>>> 55048e8 (Update kanpilot.toml)
skipFolders = [ "node_modules", ".vscode", "out", "dist", ".vscode-test" ]
skipFiles = [ ".gitignore", "package.json" ]

[[processes]]
id = "process1"
name = "To Do"

  [[processes.tasks]]
<<<<<<< HEAD
<<<<<<< HEAD
  id = "u4hlp41i6zp6jiqdr02t7v6e"
  title = "Save/Restore feature (Au Sein)"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
=======
>>>>>>> cf76f52 (update)
  id = "yjxgqfvzsgz2qxgfl8uevsgk"
  title = "HUD logic (Erik)"
  description = "<p>Fix math for values in the HUD</p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "s0lnlqpde8vdx3xbq2w3320a"
  title = "Diagonal Movement (Ed)"
=======
  id = "task1"
  title = "This is a new feature"
>>>>>>> 55048e8 (Update kanpilot.toml)
  description = ""
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

[[processes]]
id = "process2"
name = "In Progress"

  [[processes.tasks]]
  id = "gf7atui7olh18blkd8427r76"
  title = "HUD arrangement (Hender)"
  description = "<p>Move HUD to the right of the screen if hender branch</p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

  [[processes.tasks]]
  id = "task2"
<<<<<<< HEAD
  title = "Missing monochrome screens in main menu (Au sein)"
  description = "<p></p>"
=======
  title = "This is a bug should be repair"
  description = ""
>>>>>>> 55048e8 (Update kanpilot.toml)
  tag = "bug"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

<<<<<<< HEAD
  [[processes.tasks]]
  id = "u4hlp41i6zp6jiqdr02t7v6e"
  title = "Save/Restore feature (Au Sein)"
  description = "<p></p>"
  tag = "backlog"
  linkFiles = [ ]
  dueDate = ""
  checkList = [ ]
  priority = ""
  linkCommits = [ ]

=======
>>>>>>> 55048e8 (Update kanpilot.toml)
[[processes]]
id = "process3"
name = "Done"
tasks = [ ]
